@startuml
class Event {
  __Public Methods__
  +Event()
  +Event(double prob)
  ~Event()
  +double getProb() const
  +double getProbComp() const
  +std::string toString() const
  +void setProb(double prob)
  __Private Data Members__
  double prob
  __Operator Overloads__
  Event Event =
  double Event &
  void Event &=
  double Event |
  void Event |=
  double Event ^
  void Event ^=
  double Event -
  void Event -=
  Event Event ~
  bool Event ==
  bool Event <
  bool Event >
  bool Event !=
  bool Event >=
  bool Event <=
}

@enduml